baseURL = "/"
languageCode = "fr"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "LabVeilleTech"
[pagination]
  pagerSize = 5
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@lucartoon153"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showIntroContentOnHomepage = true
  showPostsOnHomepage = false
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 3 # only used if usePaginationOnHomepage is false
  sortPostsByDateOldestFirst = false
  addDot = true
  addFrame = true
  highlightColor = '#FF47B6'
  baseColor = "#1f1f1f"
  baseOffsetColor = "#eaeaea"
  headingColor = "#ffffff"
  textColor = "#ffffff"
  dotColor = "#FF47B6"
  enableGoogleFonts = true 
  googleFontsUrl = "https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap"
  fontFamilyHeading = "Poppins"
  fontFamilyParagraph = "Helvetica"
  fontFamilyMonospace = "monospace"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'accueil'
    name = 'Accueil'
    url = '/'
    weight = 1
  [[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 2
    url = "/posts/"
  [[menu.main]]
    name = "A propos"
    identifier = "about"
    weight = 3
    url = "/About/"
  [[menu.main]]
    name = "Tags"
    identifier = "tags"
    weight = 4
    url = "/tags/"